language: python

python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "pypy"

# We have to pin Jinja2 < 2.7  for Python 3.2 because 2.7 drops/breaks support:
# http://jinja.pocoo.org/docs/changelog/#version-2-7
# And Sphinx to < 1.3 for pypy3 and python 3.2 similarly.
#
# See also:
# http://stackoverflow.com/questions/18252804/syntax-error-in-jinja-2-library
#
# Twisted tests currently only work on Python 2.
matrix:
  include:
    - python: "2.6"
      env: TWISTED_REQ="Twisted==13.0.0"
    - python: "2.6"
      # Last version that supports Python 2.6.
      env: TWISTED_REQ="Twisted==15.4.0"
    - python: "2.7"
      env: TWISTED_REQ="Twisted==13.0.0"
    - python: "2.7"
      env: TWISTED_REQ="Twisted"
    - python: "3.2"
      env:
        - JINJA_REQ="jinja2<2.7, Pygments<2.0"
        - SPHINX="<1.3"
        # pip 8.0+ breaks on Python 3.2.
        - PIP="<8"
        # setuptools 19.4.1 breaks on Python 3.2.
        - SETUPTOOLS="<19.4.1"
    - python: "pypy"
      env: TWISTED_REQ="Twisted==13.0.0"
    - python: "pypy"
      env: TWISTED_REQ="Twisted"
    - python: "pypy3"
      env:
        - SPHINX="<1.3"
        - PIP="<8"
        # setuptools 19.4.1 breaks on Python 3.2.
        - SETUPTOOLS="<19.4.1"

install:
  - pip install -U pip$PIP wheel setuptools$SETUPTOOLS
  - pip install $JINJA_REQ sphinx$SPHINX $TWISTED_REQ
  - pip install .[test]

script:
  - python -m testtools.run testtools.tests.test_suite
  - make clean-sphinx docs
